AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  final-python-thumbnail

  Sample SAM Template for final-python-thumbnail

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    CodeUri: handler/
    Handler: app.lambda_handler
    Runtime: python3.8
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        THUMBNAIL_SIZE: 128
        REGION_NAME: "us-west-2"
    Layers:
      - "arn:aws:lambda:us-west-2:770693421928:layer:Klayers-p38-Pillow:4"

Resources:
  CreateTumbnailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.s3_thumbnail_generator
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 's3:*'
              Resource: '*'
      Events:
        CreateTumbnailEvents:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
  SrcBucket:
    Type: AWS::S3::Bucket

# Outputs:
  # ThumbnailApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Thumbnail function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/images/"
  # CreateTumbnailFunction:
  #   Description: "CreateTumbnailFunction Lambda Function ARN"
  #   Value: !GetAtt CreateTumbnailFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
